// western4.js - බස්නාහිර පළාත (ස්ථාන 61 - 80)

locations.push(
    { id: 161, cat: "nature", name_si: "කොළඹ වරාය නගරය (Port City) කෘත්‍රිම වෙරළ", name_en: "Port City Artificial Beach", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/1072179/pexels-photo-1072179.jpeg", desc_si: "කොළඹ අලුතින් ඉදිවූ වරාය නගරයේ ඇති අලංකාර කෘත්‍රිම වෙරළ තීරය සහ උද්‍යානයයි.", desc_en: "The beautiful artificial beach and park located within the new Colombo Port City.", reach_si: "කොළඹ කොටුවේ සිට කි.මී. 1 කි.", reach_en: "1km from Colombo Fort.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "ඇවිදීම, ජල ක්‍රීඩා", do_en: "Walking, Water sports", lat: 6.9385, lon: 79.8390, police: "011-2433333" },
    { id: 162, cat: "culture", name_si: "කේරගල රජමහා විහාරය", name_en: "Keragala Temple", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/20302000/pexels-photo-20302000.jpeg", desc_si: "කෝට්ටේ යුගයේදී ඉතා ප්‍රසිද්ධ අධ්‍යාපන මධ්‍යස්ථානයක් ලෙස පැවති ඓතිහාසික පන්සලකි.", desc_en: "A historic temple that was a famous educational center during the Kotte era.", reach_si: "හේන්පිටගෙදර සිට කි.මී. 3 කි.", reach_en: "3km from Henpitagedara.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "වන්දනා කිරීම", do_en: "Worship", lat: 7.0340, lon: 80.0380, police: "033-2222222" },
    { id: 163, cat: "nature", name_si: "නාච්චිමලේ වතුර වැටෙන ස්ථානය", name_en: "Nachchimale Area", district_si: "කළුතර", district_en: "Kalutara", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "ඉතා පිරිසිදු දිය ඇලි සහ ස්වාභාවික ජල තටාක සහිත සංචාරකයන් අතර ජනප්‍රිය ස්ථානයකි.", desc_en: "A popular spot with clean waterfalls and natural pools for bathing.", reach_si: "ඉංගිරිය නගරයේ සිට කි.මී. 2 කි.", reach_en: "2km from Ingiriya town.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "දිවා කාලය", best_en: "Daytime", do_si: "දිය නෑම", do_en: "Bathing", lat: 6.7420, lon: 80.1780, police: "034-2222222" },
    { id: 164, cat: "culture", name_si: "සැමන් දූපත", name_en: "Salmon Island", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "බෝට්ටු සවාරි සඳහා සුදුසු කැලණි ගඟ මැද පිහිටි කුඩා අලංකාර දූපතකි.", desc_en: "A small scenic island in the Kelani River, perfect for boat rides.", reach_si: "හංවැල්ල හරහා ලඟා විය හැක.", reach_en: "Accessible via Hanwella.", fee_si: "බෝට්ටු ගාස්තු", fee_en: "Boat charges", best_si: "සවස", best_en: "Evening", do_si: "බෝට්ටු සවාරි", do_en: "Boat rides", lat: 6.9050, lon: 80.0820, police: "011-2000000" },
    { id: 165, cat: "nature", name_si: "රන්වල ඇල්ල", name_en: "Ranwala Waterfall", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "ගම්පහ දිස්ත්‍රික්කයේ දොම්පේ ප්‍රදේශයේ පිහිටි කුඩා නමුත් ලස්සන දිය ඇල්ලකි.", desc_en: "A small but beautiful waterfall located in Dompe, Gampaha.", reach_si: "කිරිඳිවැල සිට කි.මී. 4 කි.", reach_en: "4km from Kirindiwela.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "දිවා කාලය", best_en: "Daytime", do_si: "විවේකය", do_en: "Relaxation", lat: 7.0120, lon: 80.1150, police: "033-2222222" },
    { id: 166, cat: "culture", name_si: "නැදීමාල බෞද්ධ සංස්කෘතික මධ්‍යස්ථානය", name_en: "Nedimala Buddhist Center", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/20302000/pexels-photo-20302000.jpeg", desc_si: "විශාල බුදු පිළිමයක් සහිත ඉතාමත් පිරිසිදු සහ සන්සුන් ආගමික ස්ථානයකි.", desc_en: "A clean and calm religious center featuring a large Buddha statue.", reach_si: "දෙහිවල නැදීමාල ප්‍රදේශයේ.", reach_en: "In Nedimala, Dehiwala.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "වන්දනා කිරීම", do_en: "Worship", lat: 6.8520, lon: 79.8880, police: "011-2738222" },
    { id: 167, cat: "beach", name_si: "උස්වැටකෙයියාව වෙරළ", name_en: "Uswetakeiyawa Beach", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/1072179/pexels-photo-1072179.jpeg", desc_si: "කොළඹ නගරයට ආසන්නව පිහිටි ජනබහුල නොවන නිස්කලංක වෙරළ තීරයකි.", desc_en: "A quiet, less crowded beach located close to Colombo city.", reach_si: "වත්තල සිට කි.මී. 5 කි.", reach_en: "5km from Wattala.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "වෙරළේ ඇවිදීම", do_en: "Beach walk", lat: 7.0150, lon: 79.8650, police: "011-2930222" },
    { id: 168, cat: "nature", name_si: "මාදම්පේ තෙත් බිම", name_en: "Madampe Wetland", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", desc_si: "වටිනා ශාක සහ පක්ෂීන් රාශියක් දැකගත හැකි තෙත් බිම් පරිසරයකි.", desc_en: "A wetland environment rich in flora and fauna.", reach_si: "පිළියන්දල හරහා ලඟා විය හැක.", reach_en: "Accessible via Piliyandala.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "පරිසරය නැරඹීම", do_en: "Nature observation", lat: 6.8020, lon: 79.9250, police: "011-2614222" },
    { id: 169, cat: "culture", name_si: "ලංකාපුර ජන කලා කේන්ද්‍රය", name_en: "Lankapura Folk Center", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/14532724/pexels-photo-14532724.jpeg", desc_si: "ශ්‍රී ලංකාවේ සාම්ප්‍රදායික හස්ත කර්මාන්ත සහ උරුමයන් ප්‍රදර්ශනය කරන ස්ථානයකි.", desc_en: "A place showcasing traditional Sri Lankan handicrafts and heritage.", reach_si: "බත්තරමුල්ල දියත උයන අසල.", reach_en: "Near Diyatha Uyana, Battaramulla.", fee_si: "රු. 100", fee_en: "LKR 100", best_si: "දිවා කාලය", best_en: "Daytime", do_si: "අධ්‍යාපනය, නැරඹීම", do_en: "Education, Sightseeing", lat: 6.8980, lon: 79.9180, police: "011-2862222" },
    { id: 170, cat: "nature", name_si: "ඔලබොඩුව මල් උයන", name_en: "Olaboduwa Flower Garden", district_si: "කළුතර", district_en: "Kalutara", img: "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg", desc_si: "විවිධ වර්ගයේ මල් සහ විසිතුරු ශාක අලෙවියට ඇති දැවැන්ත උද්‍යානයකි.", desc_en: "A massive nursery with various types of flowers and ornamental plants.", reach_si: "ගෝනපොල සිට කි.මී. 2 කි.", reach_en: "2km from Gonapola.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "මල් නැරඹීම", do_en: "Viewing plants", lat: 6.7210, lon: 79.9950, police: "034-2222222" },
    { id: 171, cat: "culture", name_si: "කොළඹ ලන්දේසි කෞතුකාගාරය", name_en: "Dutch Museum", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/20302000/pexels-photo-20302000.jpeg", desc_si: "ලන්දේසි යුගයට අයත් ගෘහ නිර්මාණ ශිල්පය සහ භාණ්ඩ ප්‍රදර්ශනය කරන ඓතිහාසික ගොඩනැගිල්ලකි.", desc_en: "A historic building displaying Dutch-era architecture and artifacts.", reach_si: "කොළඹ පිටකොටුවේ.", reach_en: "In Pettah, Colombo.", fee_si: "රු. 100", fee_en: "LKR 100", best_si: "දිවා කාලය", best_en: "Daytime", do_si: "ඉතිහාසය නැරඹීම", do_en: "Historical visit", lat: 6.9360, lon: 79.8520, police: "011-2433333" },
    { id: 172, cat: "wild", name_si: "හංවැල්ල වලව්ව අසල වනය", name_en: "Hanwella Forest Patch", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", desc_si: "කුඩා වන ලැහැබක් සහ සන්සුන් පරිසරයක පිහිටි ඓතිහාසික ප්‍රදේශයකි.", desc_en: "A historic area with a small forest patch and peaceful surroundings.", reach_si: "හංවැල්ල නගරය අසල.", reach_en: "Near Hanwella town.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "ඇවිදීම", do_en: "Walking", lat: 6.9010, lon: 80.0810, police: "011-2000000" },
    { id: 173, cat: "nature", name_si: "රෑන වැව", name_en: "Raana Lake", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "මිනුවන්ගොඩ ප්‍රදේශයේ පිහිටි නිස්කලංක සහ ස්වාභාවික වැවකි.", desc_en: "A quiet and natural lake located in Minuwangoda.", reach_si: "මිනුවන්ගොඩ නගරයේ සිට කි.මී. 3 කි.", reach_en: "3km from Minuwangoda.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "විවේකය", do_en: "Relaxing", lat: 7.1650, lon: 79.9520, police: "011-2295222" },
    { id: 174, cat: "culture", name_si: "දෝව පන්සල (බස්නාහිර)", name_en: "Dowa Western Temple", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/14532724/pexels-photo-14532724.jpeg", desc_si: "පාදුක්ක ප්‍රදේශයේ පිහිටි පැරණි සිරිත් විරිත් අගයන විහාරස්ථානයකි.", desc_en: "A temple in Padukka that values ancient traditions.", reach_si: "පාදුක්ක නගරයේ සිට විනාඩි 10 කි.", reach_en: "10 mins from Padukka town.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "වන්දනාව", do_en: "Worship", lat: 6.8420, lon: 80.1020, police: "011-2830222" },
    { id: 175, cat: "nature", name_si: "කළු ගඟේ මෝය කට", name_en: "Kalu Ganga Estuary", district_si: "කළුතර", district_en: "Kalutara", img: "https://images.pexels.com/photos/1072179/pexels-photo-1072179.jpeg", desc_si: "කළු ගඟ සාගරයට එකතු වන ඉතාමත් සුන්දර සහ පුළුල් වැලි තලාවකි.", desc_en: "The beautiful wide sandy area where the Kalu River meets the ocean.", reach_si: "කළුතර බෝධිය අසලින් ලඟා විය හැක.", reach_en: "Accessible near Kalutara Bodhiya.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "ඡායාරූපකරණය", do_en: "Photography", lat: 6.5880, lon: 79.9580, police: "034-2222222" },
    { id: 176, cat: "nature", name_si: "වේවැල්වල දිය ඇල්ල", name_en: "Wewalwala Waterfall", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "නිට්ටඹුව ප්‍රදේශයේ පිහිටි ඉතාමත් කුඩා දිය ඇල්ලක් සහිත නිහඬ ප්‍රදේශයකි.", desc_en: "A very small waterfall and quiet area located in Nittambuwa.", reach_si: "නිට්ටඹුව නගරයේ සිට කි.මී. 5 කි.", reach_en: "5km from Nittambuwa.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "විවේකය", do_en: "Relaxation", lat: 7.1450, lon: 80.1250, police: "033-2222222" },
    { id: 177, cat: "culture", name_si: "හැව්ලොක් ටවුන් ශාන්ත පීතර පල්ලිය", name_en: "St. Peter's Church", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/14532724/pexels-photo-14532724.jpeg", desc_si: "කොළඹ ප්‍රදේශයේ පිහිටි පෞරාණික වටිනාකමක් සහිත කතෝලික පල්ලියකි.", desc_en: "An old Catholic church with historical value in Colombo.", reach_si: "හැව්ලොක් පාරේ.", reach_en: "On Havelock Road.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "ආගමික වතාවත්", do_en: "Religious activities", lat: 6.8850, lon: 79.8620, police: "011-2588222" },
    { id: 178, cat: "nature", name_si: "ජාවත්ත ඇවිදින මංතීරුව", name_en: "Jawatte Walking Path", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg", desc_si: "කොළඹ 07 ප්‍රදේශයේ ඉතාමත් ලස්සනට නිර්මාණය කර ඇති ඇවිදින මංතීරුවකි.", desc_en: "A beautifully designed walking path in Colombo 07.", reach_si: "Torrington Square අසල.", reach_en: "Near Torrington Square.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "ඇවිදීම, ව්‍යායාම", do_en: "Walking, Exercise", lat: 6.9020, lon: 79.8680, police: "011-2588222" },
    { id: 179, cat: "nature", name_si: "තඹගල වැව", name_en: "Thambagala Lake", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "මීරිගම ප්‍රදේශයේ පිහිටි සොබාදහමෙන් පිරි අලංකාර වැවකි.", desc_en: "A beautiful lake surrounded by nature in Mirigama.", reach_si: "මීරිගම නගරයේ සිට කි.මී. 4 කි.", reach_en: "4km from Mirigama.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "ඡායාරූපකරණය", do_en: "Photography", lat: 7.2450, lon: 80.1280, police: "033-2222222" },
    { id: 180, cat: "culture", name_si: "විහාරමහාදේවි එළිමහන් රංග පීඨය", name_en: "Viharamahadevi Open Air Theater", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/14532724/pexels-photo-14532724.jpeg", desc_si: "විවිධ කලා කටයුතු සහ උත්සව පවත්වන කොළඹ නගර මධ්‍යයේ ඇති රංග පීඨයකි.", desc_en: "An open-air theater in the heart of Colombo used for various cultural events.", reach_si: "විහාරමහාදේවි උද්‍යානය තුළ.", reach_en: "Inside Viharamahadevi Park.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "නැරඹීම", do_en: "Watching", lat: 6.9120, lon: 79.8620, police: "011-2433333" }
);
