// western1.js - බස්නාහිර පළාත (ස්ථාන 01 - 20)

locations.push(
    { 
        id: 101, cat: "culture", 
        name_si: "ගංගාරාම විහාරය", name_en: "Gangaramaya Temple", 
        district_si: "කොළඹ", district_en: "Colombo", 
        img: "https://images.pexels.com/photos/20302000/pexels-photo-20302000.jpeg", 
        desc_si: "කොළඹ නගරයේ පිහිටි අලංකාරවත් විහාරස්ථානයකි. මෙහි ඇති කෞතුකාගාරය සහ වාර්ෂික පෙරහැර ඉතා ප්‍රසිද්ධය.",
        desc_en: "A beautiful temple in Colombo. Famous for its museum, architecture, and the annual Navam Perahera.", 
        reach_si: "කොළඹ කොටුවේ සිට ඕනෑම වාහනයකින් විනාඩි 10 කින් ලඟා විය හැක.", 
        reach_en: "10 minutes from Colombo Fort via any vehicle.",
        fee_si: "රු. 300 (විදේශිකයන්ට)", fee_en: "LKR 300 (For Foreigners)", 
        best_si: "සවස කාලය", best_en: "Evening", 
        do_si: "කෞතුකාගාරය නැරඹීම, ඡායාරූපකරණය", do_en: "Museum visit, Photography",
        lat: 6.9165, lon: 79.8580, police: "011-2433333" 
    },
    { 
        id: 102, cat: "beach", 
        name_si: "ගාලු මුවදොර පිටිය", name_en: "Galle Face Green", 
        district_si: "කොළඹ", district_en: "Colombo", 
        img: "https://images.pexels.com/photos/15900010/pexels-photo-15900010.jpeg", 
        desc_si: "මුහුදු වෙරළට මායිම්ව පිහිටි විශාල විවෘත පිටියකි. හිරු බැසීම නැරඹීමට සහ වීදි ආහාර රස විඳීමට කදිම ස්ථානයකි.",
        desc_en: "A large ocean-side urban park. Perfect for sunset watching and enjoying local street food.", 
        reach_si: "කොළඹ නගර මධ්‍යයේ පිහිටා ඇත.", 
        reach_en: "Located in the heart of Colombo.",
        fee_si: "නොමිලේ", fee_en: "Free", 
        best_si: "සවස 5 න් පසු", best_en: "After 5 PM", 
        do_si: "සරුංගල් යැවීම, රසවත් ආහාර අනුභවය", do_en: "Kite flying, Tasting street food",
        lat: 6.9248, lon: 79.8427, police: "011-2421111" 
    },
    { 
        id: 103, cat: "culture", 
        name_si: "ජාතික කෞතුකාගාරය", name_en: "National Museum", 
        district_si: "කොළඹ", district_en: "Colombo", 
        img: "https://images.pexels.com/photos/10380022/pexels-photo-10380022.jpeg", 
        desc_si: "ශ්‍රී ලංකාවේ විශාලතම කෞතුකාගාරයයි. මෙහි ලංකාවේ ඉපැරණි රජ සමයට අයත් වටිනා වස්තූන් ප්‍රදර්ශනය කෙරේ.",
        desc_en: "The largest museum in Sri Lanka, housing regalia of the country and artifacts from ancient kingdoms.", 
        reach_si: "කුරුඳුවත්ත (Cinnamon Gardens) ප්‍රදේශයේ පිහිටා ඇත.", 
        reach_en: "Located in Cinnamon Gardens, Colombo 07.",
        fee_si: "රු. 100 (දේශීය)", fee_en: "LKR 100 (Local)", 
        best_si: "උදෑසන 9 සිට සවස 5 දක්වා", best_en: "9 AM to 5 PM", 
        do_si: "ඉතිහාසය හැදෑරීම", do_en: "Learning history",
        lat: 6.9111, lon: 79.8612, police: "011-2691111" 
    },
    { 
        id: 104, cat: "culture", 
        name_si: "කැලණිය රජමහා විහාරය", name_en: "Kelaniya Temple", 
        district_si: "ගම්පහ", district_en: "Gampaha", 
        img: "https://images.pexels.com/photos/14532724/pexels-photo-14532724.jpeg", 
        desc_si: "බුදුරජාණන් වහන්සේගේ තෙවන ලංකා ගමනයෙන් පූජනීයත්වයට පත් ඓතිහාසික විහාරයකි.",
        desc_en: "A sacred historic temple hallowed by the third visit of Lord Buddha to Sri Lanka.", 
        reach_si: "කොළඹ සිට කි.මී. 10 ක් දුරින් පිහිටා ඇත.", 
        reach_en: "Located 10km away from Colombo city.",
        fee_si: "නොමිලේ", fee_en: "Free", 
        best_si: "උදෑසන හෝ සවස", best_en: "Morning or Evening", 
        do_si: "වන්දනා මාන කිරීම, සිතුවම් නැරඹීම", do_en: "Worship, Observing murals",
        lat: 6.9525, lon: 79.9208, police: "011-2911222" 
    },
    { 
        id: 105, cat: "nature", 
        name_si: "දෙහිවල සත්වෝද්‍යානය", name_en: "Dehiwala Zoo", 
        district_si: "කොළඹ", district_en: "Colombo", 
        img: "https://images.pexels.com/photos/70442/elephant-sea-lion-funny-70442.jpeg", 
        desc_si: "ආසියාවේ පැරණිතම සත්වෝද්‍යානයකි. මෙහි විවිධ වර්ගයේ සතුන් සහ පක්ෂීන් දැකගත හැක.",
        desc_en: "One of the oldest zoological gardens in Asia, home to a wide variety of animals and birds.", 
        reach_si: "දෙහිවල හන්දියේ සිට කි.මී. 1 ක් පමණ ඇතුළත පිහිටා ඇත.", 
        reach_en: "Located 1km from Dehiwala junction.",
        fee_si: "රු. 200 (දේශීය වැඩිහිටි)", fee_en: "LKR 200 (Local Adult)", 
        best_si: "දවස පුරා", best_en: "Throughout the day", 
        do_si: "සතුන් නැරඹීම, අධ්‍යාපනික චාරිකා", do_en: "Animal watching, Educational trips",
        lat: 6.8500, lon: 79.8741, police: "011-2712222" 
    },
    { 
        id: 106, cat: "beach", 
        name_si: "මීගමුව වෙරළ", name_en: "Negombo Beach", 
        district_si: "ගම්පහ", district_en: "Gampaha", 
        img: "https://images.pexels.com/photos/1007657/pexels-photo-1007657.jpeg", 
        desc_si: "ගුවන් තොටුපලට ආසන්නව පිහිටි අතිශය ජනප්‍රිය සංචාරක කලාපයකි.",
        desc_en: "A very popular tourist zone located close to the International Airport.", 
        reach_si: "කටුනායක ගුවන් තොටුපලේ සිට විනාඩි 20 කින් ලඟා විය හැක.", 
        reach_en: "20 minutes drive from Katunayake Airport.",
        fee_si: "නොමිලේ", fee_en: "Free", 
        best_si: "සවස කාලය", best_en: "Evening", 
        do_si: "මුහුදු ආහාර රස විඳීම, බෝට්ටු සංචාර", do_en: "Seafood dining, Boat rides",
        lat: 7.2348, lon: 79.8422, police: "031-2222222" 
    },
    { 
        id: 107, cat: "culture", 
        name_si: "කළුතර බෝධිය", name_en: "Kalutara Bodhiya", 
        district_si: "කළුතර", district_en: "Kalutara", 
        img: "https://images.pexels.com/photos/14101416/pexels-photo-14101416.jpeg", 
        desc_si: "ගාලු පාරේ පිහිටි ලොව ප්‍රථම කුහර සහිත චෛත්‍යය සහ පූජනීය බෝධීන් වහන්සේය.",
        desc_en: "The world's first hollow pagoda and a sacred Bodhi tree located on Galle Road.", 
        reach_si: "කොළඹ - ගාලු ප්‍රධාන පාරේ කළුතර පාලම අසල.", 
        reach_en: "Near Kalutara Bridge on Colombo-Galle main road.",
        fee_si: "නොමිලේ", fee_en: "Free", 
        best_si: "ඕනෑම වේලාවක", best_en: "Anytime", 
        do_si: "වන්දනා මාන කිරීම", do_en: "Worship",
        lat: 6.5855, lon: 79.9607, police: "034-2222222" 
    },
    { 
        id: 108, cat: "nature", 
        name_si: "විහාරමහාදේවි උද්‍යානය", name_en: "Viharamahadevi Park", 
        district_si: "කොළඹ", district_en: "Colombo", 
        img: "https://images.pexels.com/photos/10380018/pexels-photo-10380018.jpeg", 
        desc_si: "කොළඹ නගරයේ ඇති විශාලතම සහ පැරණිතම පොදු උද්‍යානයයි.",
        desc_en: "The largest and oldest public park in the city of Colombo.", 
        reach_si: "කොළඹ නගර සභාව ඉදිරිපිට පිහිටා ඇත.", 
        reach_en: "Located in front of the Colombo Town Hall.",
        fee_si: "නොමිලේ", fee_en: "Free", 
        best_si: "උදෑසන හෝ සවස", best_en: "Morning or Evening", 
        do_si: "විවේක ගැනීම, ඇවිදීම", do_en: "Relaxation, Walking",
        lat: 6.9128, lon: 79.8612, police: "011-2691111" 
    },
    { 
        id: 109, cat: "culture", 
        name_si: "නෙළුම් කුළුණ", name_en: "Lotus Tower", 
        district_si: "කොළඹ", district_en: "Colombo", 
        img: "https://images.pexels.com/photos/13444391/pexels-photo-13444391.jpeg", 
        desc_si: "දකුණු ආසියාවේ උසම ස්වයං ආධාරක ව්‍යුහය වන අතර මෙහි සිට මුළු කොළඹ නගරයම දැකගත හැක.",
        desc_en: "The tallest self-supporting structure in South Asia offering a 360-degree view of Colombo.", 
        reach_si: "ඩී.ආර්. විජයවර්ධන මාවතේ පිහිටා ඇත.", 
        reach_en: "Located on D.R. Wijewardene Mawatha, Colombo.",
        fee_si: "රු. 500 (දේශීය)", fee_en: "LKR 500 (Local)", 
        best_si: "සවස සහ රාත්‍රී කාලය", best_en: "Evening and Night", 
        do_si: "නගර සිරි නැරඹීම, භ්‍රමණය වන අවන්හල", do_en: "City view, Revolving restaurant",
        lat: 6.9298, lon: 79.8592, police: "011-2421111" 
    },
    { 
        id: 110, cat: "beach", 
        name_si: "මවුන්ට් ලැවීනියා වෙරළ", name_en: "Mount Lavinia Beach", 
        district_si: "කොළඹ", district_en: "Colombo", 
        img: "https://images.pexels.com/photos/1007657/pexels-photo-1007657.jpeg", 
        desc_si: "කොළඹට ආසන්නව පිහිටි ස්නානය කිරීමට සහ විවේක ගැනීමට සුදුසු සුන්දර වෙරළකි.",
        desc_en: "A beautiful beach near Colombo, ideal for swimming and relaxation.", 
        reach_si: "ගල්කිස්ස දුම්රිය ස්ථානයේ සිට විනාඩි 5 ක දුරක්.", 
        reach_en: "5 minutes walk from Mount Lavinia Railway Station.",
        fee_si: "නොමිලේ", fee_en: "Free", 
        best_si: "සවස කාලය", best_en: "Evening", 
        do_si: "හිරු බැසීම නැරඹීම, රාත්‍රී සාද", do_en: "Watching sunset, Night parties",
        lat: 6.8351, lon: 79.8631, police: "011-2712222" 
    }
    // මෙලෙස තවත් ස්ථාන 10ක් (111-120) මීළඟට එක් කළ හැක...
);
