// western3.js - බස්නාහිර පළාත (ස්ථාන 41 - 60)

locations.push(
    { id: 141, cat: "nature", name_si: "ලක්ෂ්මන් කිරිඇල්ල උද්‍යානය", name_en: "Lakshman Kiriella Park", district_si: "කලුතර", district_en: "Kalutara", img: "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg", desc_si: "කලු ගඟ අසල පිහිටි විවේකීව කාලය ගත කළ හැකි අලංකාර උද්‍යානයකි.", desc_en: "A beautiful riverside park in Kalutara, ideal for relaxation.", reach_si: "කලුතර නගරයේ සිට විනාඩි 5 කි.", reach_en: "5 mins from Kalutara town.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "විවේකය, ඡායාරූපකරණය", do_en: "Relaxing, Photography", lat: 6.5860, lon: 79.9650, police: "034-2222222" },
    { id: 142, cat: "culture", name_si: "කෝට්ටේ රජමහා විහාරය", name_en: "Kotte Rajamaha Viharaya", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/20302000/pexels-photo-20302000.jpeg", desc_si: "කෝට්ටේ යුගයට අයත් ඉතාමත් ඓතිහාසික වටිනාකමක් ඇති විහාරස්ථානයකි.", desc_en: "A historic temple dating back to the Kotte Kingdom era.", reach_si: "පිටකෝට්ටේ හන්දියේ සිට මීටර් 500 කි.", reach_en: "500m from Pitakotte junction.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "වන්දනා කිරීම", do_en: "Worship", lat: 6.8912, lon: 79.9025, police: "011-2852222" },
    { id: 143, cat: "beach", name_si: "පානදුර වෙරළ", name_en: "Panadura Beach", district_si: "කලුතර", district_en: "Kalutara", img: "https://images.pexels.com/photos/1072179/pexels-photo-1072179.jpeg", desc_si: "පවුලේ සැමට විනෝද විය හැකි පුළුල් වැලි සහිත වෙරළ තීරයකි.", desc_en: "A wide sandy beach perfect for family outings.", reach_si: "පානදුර නගරයේ සිට කි.මී. 1 කි.", reach_en: "1km from Panadura town.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "වෙරළේ ඇවිදීම", do_en: "Beach walk", lat: 6.7115, lon: 79.8972, police: "038-2232222" },
    { id: 144, cat: "nature", name_si: "අත්තිඩිය පක්ෂි අභයභූමිය", name_en: "Attidiya Bird Sanctuary", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", desc_si: "විවිධ පක්ෂි විශේෂ රාශියක් නැරඹිය හැකි වටිනා තෙත් බිම් කලාපයකි.", desc_en: "A wetland area rich in biodiversity and bird species.", reach_si: "බොරලැස්ගමුව හරහා ලඟා විය හැක.", reach_en: "Accessible via Boralesgamuwa.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන 6-8", best_en: "Morning 6-8 AM", do_si: "කුරුල්ලන් නැරඹීම", do_en: "Bird watching", lat: 6.8392, lon: 79.9056, police: "011-2738222" },
    { id: 145, cat: "culture", name_si: "තලංගම වැව", name_en: "Thalangama Lake", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "නාගරික පරිසරයක පිහිටි ඉතා නිහඬ සහ අලංකාර ජලජ පාරිසරික කලාපයකි.", desc_en: "A peaceful wetland ecosystem located in a suburban setting.", reach_si: "බත්තරමුල්ලේ සිට කි.මී. 3 කි.", reach_en: "3km from Battaramulla.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "ඡායාරූපකරණය, කුරුල්ලන් නැරඹීම", do_en: "Photography, Bird watching", lat: 6.8920, lon: 79.9320, police: "011-2862222" },
    { id: 146, cat: "culture", name_si: "රන්මිණිතැන්න සිනමා ගම්මානය", name_en: "Ranminithenna Village", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/14532724/pexels-photo-14532724.jpeg", desc_si: "චිත්‍රපට සහ ටෙලිනාට්‍ය රූගත කිරීම් සඳහා නිර්මාණය කළ විශේෂ ගම්මානයකි.", desc_en: "A purpose-built cinema village for film and tele-drama productions.", reach_si: "කොළඹ සිට දක්ෂිණ අධිවේගී මාර්ගය හරහා.", reach_en: "Accessible via Southern Expressway.", fee_si: "රු. 200", fee_en: "LKR 200", best_si: "දිවා කාලය", best_en: "Daytime", do_si: "නැරඹීම", do_en: "Sightseeing", lat: 6.2200, lon: 81.2000, police: "011-2000000" },
    { id: 147, cat: "beach", name_si: "ලුනාව වැව", name_en: "Lunawa Lake", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "මොරටුව ප්‍රදේශයේ පිහිටි අලංකාර වැවක් සහ ඒ අවට ඇති උද්‍යානයකි.", desc_en: "A scenic lake and park area located in Moratuwa.", reach_si: "මොරටුව දුම්රිය ස්ථානය අසල.", reach_en: "Near Moratuwa Railway Station.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "විවේකය", do_en: "Relaxing", lat: 6.7865, lon: 79.8850, police: "011-2645222" },
    { id: 148, cat: "culture", name_si: "ජාවත්ත පල්ලිය", name_en: "Jawatte Mosque", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/20302000/pexels-photo-20302000.jpeg", desc_si: "කොළඹ නගරයේ පිහිටි ඓතිහාසික සහ අලංකාර ඉස්ලාමීය ආගමික ස්ථානයකි.", desc_en: "A historic and beautiful mosque located in Colombo.", reach_si: "ජාවත්ත පාර, කොළඹ 05.", reach_en: "Jawatte Road, Colombo 05.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "දිවා කාලය", best_en: "Daytime", do_si: "වන්දනා කිරීම", do_en: "Worship", lat: 6.8965, lon: 79.8655, police: "011-2588222" },
    { id: 149, cat: "nature", name_si: "ඇලවේල්ල උද්‍යානය", name_en: "Elawella Park", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg", desc_si: "ගම්පහ නගරයට ආසන්නව පිහිටි නිහඬ සහ ලස්සන උද්‍යානයකි.", desc_en: "A quiet and beautiful park located near Gampaha town.", reach_si: "ගම්පහ හීන්දෙණිය පාරේ.", reach_en: "On Gampaha-Heendeniya road.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "ඇවිදීම", do_en: "Walking", lat: 7.0910, lon: 80.0050, police: "033-2222222" },
    { id: 150, cat: "culture", name_si: "වරණ රජමහා විහාරය", name_en: "Warana Temple", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/14532724/pexels-photo-14532724.jpeg", desc_si: "පැරණි බිතුසිතුවම් සහිත කඳු මුදුනක පිහිටි ලෙන් විහාරයකි.", desc_en: "A cave temple on a hill with ancient murals and a serene environment.", reach_si: "යක්කල සිට කි.මී. 5 කි.", reach_en: "5km from Yakkala.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "කඳු නැගීම, වන්දනාව", do_en: "Hiking, Worship", lat: 7.1050, lon: 80.0450, police: "033-2222222" },
    { id: 151, cat: "nature", name_si: "කලපළුවාව තෙත් බිම", name_en: "Kalapaluwawa Wetland", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", desc_si: "රාජගිරිය ප්‍රදේශයේ පිහිටි ජෛව විවිධත්වයෙන් පිරි තෙත් බිම් ප්‍රදේශයකි.", desc_en: "A biodiversity-rich wetland area located in Rajagiriya.", reach_si: "බත්තරමුල්ලේ සිට විනාඩි 10 කි.", reach_en: "10 mins from Battaramulla.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "ස්වභාව සෞන්දර්යය", do_en: "Nature watching", lat: 6.9080, lon: 79.9150, police: "011-2862222" },
    { id: 152, cat: "beach", name_si: "වැල්ලවත්ත වෙරළ", name_en: "Wellawatte Beach", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/1072179/pexels-photo-1072179.jpeg", desc_si: "දුම්රිය මාර්ගයට සමාන්තරව පිහිටි සවසට ඇවිදීමට සුදුසු වෙරළකි.", desc_en: "A popular city beach running parallel to the railway tracks.", reach_si: "වැල්ලවත්ත දුම්රිය ස්ථානය අසල.", reach_en: "Near Wellawatte Railway Station.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "හිරු බැසීම නැරඹීම", do_en: "Sunset watching", lat: 6.8750, lon: 79.8580, police: "011-2588222" },
    { id: 153, cat: "culture", name_si: "මාලිගාතැන්න ආරණ්‍යය", name_en: "Maligatenna Hermitage", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/14532724/pexels-photo-14532724.jpeg", desc_si: "ඉතා උස ස්ථානයක පිහිටි අලංකාර දර්ශන පෙනෙන විහාරස්ථානයකි.", desc_en: "A hermitage located on a high peak offering breathtaking views.", reach_si: "මල්වාන හරහා ලඟා විය හැක.", reach_en: "Accessible via Malwana.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "කඳු නැගීම", do_en: "Hiking", lat: 7.0250, lon: 80.0650, police: "033-2222222" },
    { id: 154, cat: "wild", name_si: "තලංගම පක්ෂි කලාපය", name_en: "Thalangama Bird Zone", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", desc_si: "සංක්‍රමණික කුරුල්ලන් නැරඹීමට බස්නාහිර පළාතේ ඇති හොඳම ස්ථානයකි.", desc_en: "One of the best spots in the Western province for migratory bird watching.", reach_si: "පැලවත්ත හන්දියේ සිට කි.මී. 2 කි.", reach_en: "2km from Pelawatte junction.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන 6.00", best_en: "Morning 6 AM", do_si: "කුරුල්ලන් නැරඹීම", do_en: "Bird watching", lat: 6.8850, lon: 79.9400, police: "011-2862222" },
    { id: 155, cat: "nature", name_si: "පෝරේ වනාන්තරය", name_en: "Pore Forest", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg", desc_si: "අතුරුගිරිය ප්‍රදේශයේ පිහිටි කුඩා නමුත් ඝන වනාන්තර ප්‍රදේශයකි.", desc_en: "A small but dense forest patch located in Athurugiriya.", reach_si: "අතුරුගිරිය නගරයේ සිට විනාඩි 10 කි.", reach_en: "10 mins from Athurugiriya.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "උදෑසන", best_en: "Morning", do_si: "ස්වභාවික ඇවිදීම", do_en: "Nature walks", lat: 6.8720, lon: 79.9750, police: "011-2741222" },
    { id: 156, cat: "beach", name_si: "ගල්කිස්ස හෝටල් වෙරළ", name_en: "Mount Lavinia Hotel Beach", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/1072179/pexels-photo-1072179.jpeg", desc_si: "ඓතිහාසික ගල්කිස්ස හෝටලය අසල ඇති ඉතා සුන්දර වෙරළ තීරයකි.", desc_en: "A beautiful beach strip near the historic Mount Lavinia Hotel.", reach_si: "ගල්කිස්ස හන්දියේ සිට කි.මී. 1 කි.", reach_en: "1km from Mt. Lavinia junction.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "විනෝද වීම", do_en: "Leisure", lat: 6.8350, lon: 79.8620, police: "011-2738222" },
    { id: 157, cat: "culture", name_si: "ජයවර්ධනපුර කෝට්ටේ කෞතුකාගාරය", name_en: "Kotte Museum", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/20302000/pexels-photo-20302000.jpeg", desc_si: "කෝට්ටේ රාජධානියේ නටබුන් සහ පුරාවස්තු තබා ඇති ස්ථානයකි.", desc_en: "A museum housing artifacts and ruins from the Kotte Kingdom.", reach_si: "ඇතුල්කෝට්ටේ හන්දිය අසල.", reach_en: "Near Ethul Kotte junction.", fee_si: "රු. 50", fee_en: "LKR 50", best_si: "දිවා කාලය", best_en: "Daytime", do_si: "ඉතිහාසය ඉගෙනීම", do_en: "Learning history", lat: 6.8950, lon: 79.9120, police: "011-2852222" },
    { id: 158, cat: "nature", name_si: "බියගම පරිසර උද්‍යානය", name_en: "Biyagama Eco Park", district_si: "ගම්පහ", district_en: "Gampaha", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "කැලණි ගඟ අසබඩ පිහිටි පරිසර හිතකාමී විවේකී ස්ථානයකි.", desc_en: "An eco-friendly relaxation spot located along the Kelani River.", reach_si: "බියගම නිදහස් වෙළඳ කලාපය අසල.", reach_en: "Near Biyagama Free Trade Zone.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "විවේකය", do_en: "Relaxing", lat: 6.9450, lon: 79.9850, police: "011-2401222" },
    { id: 159, cat: "beach", name_si: "වෙලීවිට ගං ඉවුර", name_en: "Weliwita Riverside", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg", desc_si: "කැලණි ගඟ අයිනේ විවේකීව සිටිය හැකි අලංකාර ස්ථානයකි.", desc_en: "A scenic riverside spot along the Kelani River in Kaduwela.", reach_si: "කඩුවෙල සිට කි.මී. 2 කි.", reach_en: "2km from Kaduwela.", fee_si: "නොමිලේ", fee_en: "Free", best_si: "සවස", best_en: "Evening", do_si: "විවේකය", do_en: "Relaxing", lat: 6.9380, lon: 79.9620, police: "011-2539222" },
    { id: 160, cat: "culture", name_si: "කොළඹ කොටුව දුම්රිය කෞතුකාගාරය", name_en: "Railway Museum", district_si: "කොළඹ", district_en: "Colombo", img: "https://images.pexels.com/photos/20302000/pexels-photo-20302000.jpeg", desc_si: "ශ්‍රී ලංකාවේ දුම්රිය ඉතිහාසය විදහා දක්වන පැරණි එන්ජින් සහ උපකරණ ඇති ස්ථානයකි.", desc_en: "A museum showcasing the history of Sri Lankan railways with old engines and equipment.", reach_si: "කොළඹ කොටුව දුම්රිය ස්ථානය තුළ.", reach_en: "Inside Colombo Fort Railway Station.", fee_si: "රු. 100", fee_en: "LKR 100", best_si: "උදෑසන", best_en: "Morning", do_si: "නැරඹීම", do_en: "Sightseeing", lat: 6.9340, lon: 79.8500, police: "011-2433333" }
);
